version: '3'
services:

  postgres:
    image: postgres:16.1
    container_name: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    env_file:
      - /src/core/.env
#
  api_transcrib:
    build: .
    command: bash entrypoint.sh
    env_file:
      - src/core/.env
    image: api_transcrib
    expose:
      - "8000"
    ports:
      - "8000:8000"



volumes:
  pgdbdata:
