version: '3'
services:
  redis:
    image: redis:7.2.4
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf

  postgres:
    image: postgres:16.1
    container_name: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    env_file:
      - /src/core/.env

  transcrib_service:
    build: .
    depends_on:
      - redis
      - postgres
    command: bash entrypoint.sh
    env_file:
      - src/core/.env
    image: transcrib_service
    expose:
      - "8000"
    ports:
      - "8000:8000"

volumes:
  pgdbdata:
